-- Author
-- | Book
-- | BookAuthor
-- | BookCondition
-- | BookReview
-- Category
-- | ConditionEvaluator |
-- | Owner
-- | OwnersBook
-- | Publisher
-- | Reviewer
-- State
-- Path: src/inner-join.sql
